name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: self-hosted
    steps:
    # Checkout the code
    - uses: actions/checkout@v3

    # Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # Install Python dependencies for backend
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
      working-directory: 'backend'

    # Set PYTHONPATH
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      working-directory: 'backend'
    
    # Run Python unittests
    - name: Run Python Tests
      run: |
        python -m unittest discover
      working-directory: 'backend/tests'

    # Run Flake8 linting
    - name: Run Flake8
      run: flake8 .
      working-directory: './backend'

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install Node.js dependencies for frontend
    - name: Install Node.js Dependencies
      run: npm install
      working-directory: ./frontend

    # Run ESLint
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      working-directory: ./frontend

    # Run Jest tests
    - name: Run Jest Tests
      run: npm test
      working-directory: ./frontend

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image for Backend
      run: |
        docker build -t --platform linux/amd64 kennedyemeruem/courseswap-backend:latest ./backend
        docker push kennedyemeruem/courseswap-backend:latest

    - name: Build and Push Docker Image for Frontend
      run: |
        docker build -t --platform linux/amd64 kennedyemeruem/courseswap-frontend:latest ./frontend
        docker push kennedyemeruem/courseswap-frontend:latest